### ISSUE TITLE
Kleinigkeit: Typo in der Beschreibung

### ISSUE THREAD

**Issue by silen72** [PaulGoldschmidt/OSAMD#6]
Du hast "A project by Paul Goldschmidt to meaure the quality of air indoors" geschrieben. Das soll vermutlich "A project by Paul Goldschmidt to mea__**s**__ure the quality of air indoors" heißen.

**Comment by PaulGoldschmidt** [comment]
Danke für den Tipp! Ist gefixed 🚀
